version: '3.8'

services:
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
    volumes:
      - .:/app
    depends_on:
      - db_setup

  db_setup:
    build: .
    command: bash -c "bundle exec rails db:migrate && bundle exec rails runner 'VideoDataExtractor.extract_and_upsert_videos'"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=production